Repository Ant-Shell/rancid-tomatillos, pull requests merged in 2022-10, with the labels that each got.

#12 Components/app
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/MovieCardContainer/MovieCardContainer.css
  src/components/MovieCardContainer/MovieCardContainer.js
  src/index.js
  src/movieData.js
Labels: MVP

#16 Feature/fetch
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
Labels: MVP

#20 Add error handling to display error in console log
  src/apiCalls.js
Labels: MVP

#21 Css/styling
  src/assets/A&W Film Reviews-Red.png
  src/assets/A&W Film Reviews-Transparent.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MovieCardContainer/MovieCardContainer.css
  src/components/MovieCardContainer/MovieCardContainer.js
  src/individualMovieData.js
  src/movieData.js
Labels: enhancement

#23 Write CSS for individual movie view, adjust other CSS as needed.
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/MovieCardContainer/MovieCardContainer.css
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement

#24 Css/styling
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/MovieCardContainer/MovieCardContainer.css
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement

#26 Feature/configure router
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/SingleMovie/SingleMovie.js
  src/index.js
Labels: MVP

#29 Feature/cypress
  cypress.config.js
  cypress/e2e/all-movie.cy.js
  cypress/e2e/individual-movie.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/Card/Card.js
  src/components/SingleMovie/SingleMovie.js
Labels: MVP

#34 Feature/error page
  src/assets/Countdown.gif
  src/assets/ErrorScreen.png
  src/components/App/App.js
  src/components/ErrorPage/ErrorPage.css
  src/components/ErrorPage/ErrorPage.js
  src/components/LoadingPage/LoadingPage.css
  src/components/LoadingPage/LoadingPage.js
Labels: Wishlist

#39 Refactor/more movies
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/MovieCardContainer/MovieCardContainer.js
Labels: enhancement

#40 Render error screen when errors exist, render loading screen, adjust …
  src/components/App/App.js
  src/components/ErrorPage/ErrorPage.css
  src/components/ErrorPage/ErrorPage.js
  src/components/SingleMovie/SingleMovie.js
Labels: MVP

#41 Cypress/intercepts stubbing
  .gitignore
  cypress/e2e/all-movie.cy.js
  cypress/e2e/individual-movie.cy.js
  cypress/fixtures/emptyData.json
  cypress/fixtures/example.json
  cypress/fixtures/movieData.json
  cypress/fixtures/singleMovieData1.json
  cypress/fixtures/singleMovieData2.json
  package-lock.json
  package.json
  src/components/ErrorPage/ErrorPage.js
  src/components/LoadingPage/LoadingPage.js
  src/components/SingleMovie/SingleMovie.js
Labels: MVP

#42 Refactor for env file usage
  .gitignore
  cypress/e2e/all-movie.cy.js
  cypress/e2e/individual-movie.cy.js
  cypress/fixtures/singleMovieData2.json
Labels: enhancement, MVP

#43 Refactor/rating display
  cypress/e2e/individual-movie.cy.js
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement, Wishlist

#45 Refactor/styling
  cypress/e2e/ErrorScreen.cy.js
  package-lock.json
  package.json
  src/components/LoadingPage/LoadingPage.css
  src/components/LoadingPage/LoadingPage.js
Labels: MVP

#46 Add Swiper for carousel, minor css tweaks to optimize appearance
  package-lock.json
  package.json
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/MovieCardContainer/MovieCardContainer.css
  src/components/MovieCardContainer/MovieCardContainer.js
  src/components/SingleMovie/SingleMovie.js
Labels: MVP, Wishlist

#47 Refactor/styling
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: MVP, Wishlist

#48 Feature/footer
  cypress/e2e/ErrorScreen.cy.js
  cypress/e2e/all-movie.cy.js
  cypress/e2e/individual-movie.cy.js
  src/assets/A&W Film Reviews-Transparent.png
  src/assets/AWFilmReviews-Transparent.png
  src/assets/github.png
  src/assets/linkedin.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MovieCardContainer/MovieCardContainer.css
Labels: MVP, Wishlist

#49 Feature/search functionality
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MovieCardContainer/MovieCardContainer.js
  src/components/MovieSearch/MovieSearch.css
  src/components/MovieSearch/MovieSearch.js
  src/components/SingleMovie/SingleMovie.js
Labels: Wishlist

#50 Feature/trailers
  src/apiCalls.js
  src/components/App/App.css
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: Wishlist

#51 Cypress/search functionality
  cypress/e2e/all-movie.cy.js
  src/components/App/App.css
  src/components/App/App.js
Labels: enhancement

#54 Add last pass of refactoring
  src/components/App/App.js
  src/components/ErrorPage/ErrorPage.js
  src/components/Header/Header.js
  src/components/LoadingPage/LoadingPage.js
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement
